[ical]
url = URL to CALDAV.ics
username = user to access caldav file 
password = password to access caldav file
auth_method = basic
timeout = 300
max_retries = 2
retry_delay = 10

[smtp]
server = relay server to send invoice pdf 
port = 465
sender_email = mail address invoice mail coming from
recipient_email = mail address invoice mail going to
use_starttls = true
use_ssl = false

[pdf]
logo_path = logo.jpg

[invoice_header]
firma = COMPANY
adresse = Street 1
telefon = +49 123
email = mail address on the invoice pdf signature
